### ISSUE TITLE
Bug: Wrong generated global type file import (Typescript)

### ISSUE THREAD

**Issue by stnwk** [apollographql/apollo-cli#557] opened 2018-08-21 11:26 UTC
Hi everyone :)

Since https://github.com/apollographql/apollo-cli/pull/520 by @danilobuerger landed I noticed the following:

When a `globalTypes.ts` file is generated and the the `--outputFlat` option is used, the `outputPath` is being ignored in generated type files (at least for the import statement of the `globalTypes` file).

It outputs:

```ts
import { SomeGlobalTypes, ShouldBe, Here } from "globalTypes";
```

when it should really be:

```ts
import { SomeGlobalTypes, ShouldBe, Here } from "./globalTypes";
```

Notice the incorrect path in the first example.

If you need more details, please let me know!

**Comment by danilobuerger** [comment] 2018-08-21 11:55
Duplicate of #543, fixed in #544

**Comment by lirbank** [comment] 2018-08-22 23:44
Yeah, this has been fixed a while ago (12 days ago) but it has not yet been published.

@shadaj is there anything preventing a new release? Would be awesome to have the fix published.

**Comment by shadaj** [comment] 2018-08-23 01:14
v1.7.1 has been published with the latest fixes included! Apologies for the late release, I just started college this week so my schedule's been packed with orientation activities.

**Closed by shadaj** 2018-08-23 01:14 UTC

**Comment by johannesnagl** [comment] 2018-08-23 09:52
> I just started college this week so my schedule's been packed with orientation activities

@shadaj all the best for your college years! Have fun!
